// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GaController from "./ga_controller"
application.register("ga", GaController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostModalController from "./post_modal_controller"
application.register("post-modal", PostModalController)
