FROM ruby:3.2.2

# Railsアプリの作業ディレクトリ
WORKDIR /app

# 必要パッケージ
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Gemfileだけ先にコピーしてbundle install（キャッシュ効かせる）
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリのソースコードを全部コピー
COPY . .

# 開発モード前提
ENV RAILS_ENV=development

# ポート・起動コマンド（bin/rails s）
EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
